name: CD
run-name: ${{ github.actor }} is creating a cd

on:
  push:
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALEX_DEVOPS }}
          password: ${{ secrets.ALEX_PW }}
